In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

# Pytorch Basics

In [19]:
x = torch.ones(3,2)
print(x)
x = torch.zeros(3,2)
print(x)
x = torch.randn(3,3)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[ 0.9556, -0.1201,  2.1690],
        [ 1.0425, -1.9769,  1.0871],
        [ 0.0370, -0.3693,  0.0922]])


In [21]:
x = torch.empty(3,3)
print(x)

y = torch.zeros_like(x)
print(y)

tensor([[2.3704e-08, 4.5674e-41, 1.4536e+21],
        [3.0879e-41, 4.4842e-44, 0.0000e+00],
        [1.7937e-43, 0.0000e+00, 1.4536e+21]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [26]:
x =torch.linspace(0,1,steps=11)
print(x)

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])


In [39]:
x = torch.tensor([[1,2],
                  [3,4], 
                  [5,6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [42]:
print(x.size())
print(x[:2, 0:1])

torch.Size([3, 2])
tensor([[1],
        [3]])


In [41]:
y = x[1,1]
print(y.item())

4


In [44]:
print(x)

y = x.view(2,3)  # reshape
z = x.view(6,-1)
print(y)
print(z)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [46]:
a = torch.ones(3,3)
b = torch.ones(3,3)*2
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [-1., -1., -1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])


In [48]:
c = a.add(b)
print(a)
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [49]:
c = a.add_(b)  # updates a as well
print(a)
print(c)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


# CPU vs GPU

In [2]:
%%time

for i in range(1):
    x = np.random.randn(10000,10000)
    y= np.random.randn(10000,10000)
    z = np.matmul(x,y)

CPU times: user 1min 9s, sys: 564 ms, total: 1min 10s
Wall time: 40.1 s


In [3]:
%%time

for i in range(1):
    x = torch.randn([10000,10000])
    y = torch.randn([10000,10000])
    z = torch.matmul(x,y)

CPU times: user 32 s, sys: 491 ms, total: 32.5 s
Wall time: 18 s


In [5]:
arr = np.ones((4,3))

In [6]:
arr_torch = torch.from_numpy(arr)

In [16]:
print(arr)
print(arr_torch)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
arr_torch_1 = torch.randn([4,4])
arr_numpy_1 = arr_torch_1.numpy()

In [12]:
print(arr_torch_1)
print(arr_numpy_1)

tensor([[-1.7610,  1.8062,  2.1688,  0.9464],
        [-1.0032,  0.4920, -0.6261, -0.9566],
        [ 0.1397, -0.7095, -1.0547, -0.7314],
        [-0.1855,  1.5163,  0.4081, -0.3007]])
[[-1.7609632   1.8061855   2.168805    0.9464382 ]
 [-1.0032352   0.49198866 -0.6261226  -0.9566483 ]
 [ 0.13966207 -0.7094885  -1.0547111  -0.73141515]
 [-0.18548816  1.5163004   0.4081175  -0.30071533]]


In [4]:
print(torch.cuda.get_device_name())
print(torch.cuda.device(0))

GeForce 940MX


In [2]:
#*****************************
cuda0 = torch.device('cuda:0')
#*****************************

In [19]:
%%time

for i in range(10):
    x = torch.randn([10000,10000],device=cuda0)
    y = torch.randn([10000,10000],device=cuda0)
    z = torch.matmul(x,y)

CPU times: user 887 µs, sys: 506 µs, total: 1.39 ms
Wall time: 1.41 ms


# AutoGrad

In [110]:
w = torch.randn([2,1], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

x = torch.randn([20,2])
y = torch.from_numpy( 5*np.sum(x.numpy(),axis=1,keepdims=True) +2 )

for _ in range(200):
    
    y_hat = torch.matmul(x,w)+b
    loss = torch.sum((y-y_hat)**2)  
    
    loss.backward()
    print(b.item())
    with torch.no_grad():
        w -= 0.01*w.grad
        b -= 0.01*b.grad
        w.grad.zero_()
        b.grad.zero_()
        
print(w,b)  

1.0
1.8771047592163086
2.182447671890259
2.2452340126037598
2.216661214828491
2.1628901958465576
2.110424518585205
2.067969560623169
2.0367579460144043
2.0152785778045654
2.0013344287872314
1.9928582906723022
1.9881703853607178
1.9860048294067383
1.9854507446289062
1.9858753681182861
1.9868513345718384
1.9880980253219604
1.9894373416900635
1.9907605648040771
1.9920053482055664
1.9931401014328003
1.9941520690917969
1.9950402975082397
1.9958107471466064
1.9964733123779297
1.9970388412475586
1.9975191354751587
1.9979251623153687
1.9982672929763794
1.9985547065734863
1.9987956285476685
1.9989972114562988
1.999165654182434
1.9993062019348145
1.9994232654571533
1.9995207786560059
1.99960196018219
1.9996694326400757
1.9997254610061646
1.9997721910476685
1.9998109340667725
1.9998431205749512
1.9998698234558105
1.999891996383667
1.9999103546142578
1.9999256134033203
1.9999382495880127
1.9999487400054932
1.99995756149292
1.9999648332595825
1.9999709129333496
1.9999758005142212
1.9999799728393555